[[language]]
name = "git-config"
scope = "source.gitconfig"
file-types = ["gitconfig", { glob = ".gitmodules" }, { glob = ".gitconfig" }, { glob = ".git/config" }, { glob = ".config/git/config" }, { glob = "home/git/gitconfig" }]
injection-regex = "git-config"
comment-token = "#"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "jsonc"
scope = "source.jsonc"
file-types = ["jsonc", {glob = "home/waybar/config"} ]
comment-token = "//"
indent = { tab-width = 4, unit = " " }
